######################################################################
# Automatically generated by qmake (3.0) pe kesä 12 20:54:37 2015
######################################################################

TEMPLATE = app
TARGET = pcrio
INCLUDEPATH += .

# Input
HEADERS += pcrdef.h pcrio.h
SOURCES += pcrio.c
